In [2]:
import pandas as pd
import numpy as np

from string import punctuation
from nltk.corpus import stopwords
from nltk import word_tokenize

In [3]:
stop_words = stopwords.words('english') + list(punctuation)

def tokenize(text):
    words = word_tokenize(text)
    words = [w.lower() for w in words]
    return [w for w in words if w not in stop_words and not w.isdigit()]

In [4]:
df = pd.read_csv('news.csv')
df.head()

id                                           headline  \
0  uid-1                          Market Advances 5.12 More   
1  uid-2  District Boosts Request For Anti-Terrorism Aid...   
2  uid-3              Election? Here's How You Do It, Mate.   
3  uid-4                              The Biggest Boom Ever   
4  uid-5                         Economic Aide Sees Uptrend   

                                                text  
0  NEW YORK (AP) - A prime rate reduction by New ...  
1  Mayor Anthony A. Williams petitioned the White...  
2  From our downunder perspective here in Austral...  
3  We are about to rewrite history. Unless a rece...  
4  Sedate and scholarly Dr. Arthur Burns, the ex-...

In [5]:
# tokenized all the text and removed punctuations
df['text'].apply(lambda x: tokenize(x))

0       [new, york, ap, prime, rate, reduction, new, y...
1       [mayor, anthony, a., williams, petitioned, whi...
2       [downunder, perspective, australia, united, st...
3       [rewrite, history, unless, recession, begins, ...
4       [sedate, scholarly, dr., arthur, burns, ex-col...
5       [statistics, enormous, costs, employee, drug, ...
6       [global, markets, ended, third, quarter, much,...
7       [consumer, borrowing, surged, july, mainly, re...
8       [washington, --, unexpected, decline, septembe...
9       [--, --, --, --, --, --, --, --, --, --, --, -...
10      [price, america, online, inc., 's, stock, surg...
11      [david, m., kennedy, next, secretary, u.s., tr...
12      [new, york, nov., 12���presi-de'nt, bush, poli...
13      [washington, --, general, motors, corp., chair...
14      [one, big, problems, us, life, never, get, rea...
15      [business, productivity, second, quarter, dete...
16      [washington, nice, place, visit, glad, 're, li...
17      [presi

In [6]:
vocab = set()
for i in range(len(df['headline'])):
    words = tokenize(df['headline'][i])
    vocab.update(words)
    
vocab = list(vocab)
word_index = {w: idx for idx, w in enumerate(vocab)}

VOCABULARY_SIZE = len(vocab)
DOCUMENTS_COUNT = len(df['headline'])
 
print(VOCABULARY_SIZE, DOCUMENTS_COUNT)

6003 3000


In [7]:
word_index

{'plane': 0,
 'manufacturers': 1,
 'thitrstlny': 2,
 'ingenuity': 3,
 'lengthy': 4,
 'globalization': 5,
 'circon': 6,
 'victory': 7,
 'frb': 8,
 'inns': 9,
 'preventing': 10,
 'giant': 11,
 "'just": 12,
 'lose': 13,
 'aisles': 14,
 'reportedly': 15,
 'tweaking': 16,
 'departments': 17,
 'santorum': 18,
 'men': 19,
 'term': 20,
 "'nobody": 21,
 'happened': 22,
 'vacancies': 23,
 'ou': 24,
 'knocking': 25,
 'ca': 26,
 'issue': 27,
 'u.k.': 28,
 'repay': 29,
 'cards': 30,
 'i^asljtnsiton': 31,
 'hybrid': 32,
 'misery': 33,
 'yuan': 34,
 'pitch': 35,
 'interbank': 36,
 'meeting': 37,
 'buckle': 38,
 'oil-exporting': 39,
 'meant': 40,
 'beefing': 41,
 'prescribes': 42,
 'myths': 43,
 'manage': 44,
 'need': 45,
 'washing': 46,
 'truth-len': 47,
 'narrows': 48,
 'defies': 49,
 'unwanted': 50,
 'moynihan': 51,
 'for-profit': 52,
 'large': 53,
 'entering': 54,
 '�ۢr': 55,
 'charity': 56,
 'ballot': 57,
 'eyes': 58,
 'president': 59,
 'auto-industry': 60,
 'medium': 61,
 'downward': 62,
 'award

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
 
tfidf = TfidfVectorizer(stop_words=stop_words, tokenizer=tokenize, vocabulary=vocab)

# Fit the TfIdf model
X = tfidf.fit_transform(df['text'])

f:\envs\env1\lib\site-packages\sklearn\feature_extraction\text.py:300: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ["'d", "'ll", "'re", "'s", "'ve", '``', 'could', 'might', 'must', "n't", 'need', 'sha', 'wo', 'would'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


In [9]:
y = X.toarray()

In [22]:
train

In [10]:
df2.head()

NameError: name 'df2' is not defined

In [33]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=150, random_state=0).fit(y)

kmeans.cluster_centers_

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.08420217e-19,  4.33680869e-19,  0.00000000e+00, ...,
         6.46701330e-03, -8.13151629e-20,  4.33680869e-18],
       [-5.42101086e-20,  4.33680869e-19,  0.00000000e+00, ...,
         2.16840434e-19,  0.00000000e+00,  4.19755018e-03],
       ...,
       [ 1.30104261e-18,  4.78051316e-04,  0.00000000e+00, ...,
         2.66501856e-03, -6.23416249e-19,  3.99753902e-03],
       [-1.08420217e-19,  7.46354864e-03,  0.00000000e+00, ...,
         4.33680869e-19, -2.71050543e-20,  5.24565402e-03],
       [ 1.48124644e-02,  4.33680869e-19,  0.00000000e+00, ...,
         0.00000000e+00,  2.71050543e-20,  1.15417563e-02]])

In [12]:
kmeans.labels_

array([3, 7, 7, ..., 7, 5, 6])

In [13]:
z = kmeans.predict(y)

In [14]:
z

array([3, 7, 7, ..., 7, 5, 6])

In [15]:
y

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.05767406],
       ...,
       [0.        , 0.        , 0.        , ..., 0.09071115, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [34]:
from sklearn.metrics import silhouette_score

print(silhouette_score(y, kmeans.labels_))

0.013256346623110555


In [ ]:
from sklearn.decomposition import PCA

for centers in range(2, 11):
    for components in [2,3,20,30,40,50,100,200,300,400,500,1000,1500,2000]:
        pca = PCA(n_components=components)
        pca_result = pca.fit_transform(y)
        kmeans = KMeans(n_clusters=centers, random_state=0).fit(pca_result)
        print(f'components:{components} : centers:{centers} : score:{silhouette_score(y, kmeans.labels_)}')

components:2 : centers:2 : score:0.004184917190323416
components:3 : centers:2 : score:0.004228520218004784
components:20 : centers:2 : score:0.0039121250386243665
components:30 : centers:2 : score:0.0038746058564580795
components:40 : centers:2 : score:0.003882390183858778
components:50 : centers:2 : score:0.004028963164352967
components:100 : centers:2 : score:0.003887808630017909
components:200 : centers:2 : score:0.004003973782626552
components:300 : centers:2 : score:0.0042219919781068755
components:400 : centers:2 : score:0.004125068992604411
components:500 : centers:2 : score:0.004081472841846904


In [17]:
from sklearn.decomposition import PCA
pca = PCA(n_components=199)
pca_result = pca.fit_transform(y)

In [47]:
print(pca_result)

[[ 2.36589523e-01 -8.54386025e-02  3.84836605e-02 ...  1.18173341e-02
  -7.00664809e-03 -1.88663246e-02]
 [-6.12205250e-02 -7.84312336e-02 -1.10469137e-04 ... -1.42354566e-02
   1.50401516e-02 -5.52101402e-02]
 [-7.19806063e-02 -8.82598492e-02 -2.32343459e-02 ...  2.48751710e-02
   2.65699944e-02  9.36983636e-03]
 ...
 [-3.28742480e-02 -6.09589623e-02 -1.51927854e-02 ...  4.40239669e-02
   4.81703387e-03  1.58569511e-02]
 [-2.07879162e-02  5.98982230e-02  1.70632667e-02 ... -7.72615687e-03
   5.15538560e-02 -2.76975315e-02]
 [ 4.46690925e-03 -2.32822714e-02  3.07707076e-02 ...  1.52007705e-04
   1.64494809e-03  1.55842233e-02]]


In [18]:
pca_result[:, 0]

array([ 0.32650421, -0.06654801, -0.08476043, ..., -0.02594891,
       -0.03804448,  0.00970983])

In [19]:
import matplotlib.pyplot as plt
plt.scatter(pca_result[:, 0], pca_result[:, 1])

In [20]:
kmeans = KMeans(n_clusters=3, random_state=0).fit(pca_result)
print(kmeans.cluster_centers_)
print(kmeans.labels_)
print(silhouette_score(y, kmeans.labels_))

[[-9.60905972e-03  1.22098230e-01 -2.64006751e-03  2.27920616e-02
   8.22694822e-03 -1.06489553e-02  1.25899991e-02 -4.75180263e-03
  -7.95670803e-04  7.29408283e-03 -5.20271286e-03 -1.92306134e-03
   2.74107544e-04  3.63228079e-03 -8.91290550e-03 -2.44842184e-04
  -2.67082921e-03 -9.89613437e-04 -3.91022614e-03  3.67313758e-04
   4.99136847e-03  1.22925159e-03  2.49783234e-03  1.59970787e-03
   3.47741350e-03 -6.82544975e-04 -1.52962589e-04  1.37763271e-03
  -1.89031806e-03  8.18379888e-04 -2.50303678e-03 -2.95095350e-03
   1.11790669e-03  2.00148258e-03  1.22735534e-03 -3.42625922e-03
  -1.10505322e-03  2.71764927e-03  3.48800906e-04 -1.94540029e-03
   2.44421751e-04 -1.66216352e-03 -9.58232393e-04 -1.47975256e-03
  -6.85437597e-04  3.39885914e-03 -7.81801798e-04  6.87948284e-04
   1.81533754e-03  3.11418882e-04 -1.03734485e-04 -2.21051531e-05
   1.30708810e-03 -2.62769858e-03  6.84174001e-04  2.13989624e-03
  -1.58773055e-03  4.16636378e-04  9.29108261e-04  6.41610312e-04
   1.60925

0.0076652503366352615
